VM: optionally preserve nic ordering
OpenNebula/terraform-provider-opennebula pull request #148
Opened 2021-08-26 19:06 UTC by treywelsh

Allow (optionally) to preserve VM nic ordering on update

2021-09-13 09:09 UTC, jaypif requested changes
Can you add test case for this. It is really important to have unit test on this feature.

2021-09-13 09:09 UTC, jaypif commented on opennebula/resource_opennebula_virtual_machine.go
> +			// disks with greater nic ID should be detached
NICs instead of disks

2021-09-29 10:46 UTC, treywelsh commented
test case was added in last branch version I pushed

2021-10-01 12:50 UTC, jaypif approved these changes

2021-10-01 12:50 UTC, merged