WIP: F-26: new vm template attributes
OpenNebula/terraform-provider-opennebula pull request #154
Opened 2021-09-02 04:47 UTC by treywelsh

adds hypervisor, description, user_inputs, sched_requirements sections to VM and Template resources schemas.

There is no acceptance test for these attributes for now

2021-09-13 10:11 UTC, jaypif commented on opennebula/resource_opennebula_image.go
> +	if d.HasChange("description") {
why not doing update once if there are several updates like it is already the case for templates or VMs ?

2021-09-13 10:11 UTC, jaypif commented on opennebula/shared_schemas.go
> +		Description: "Boolean expression that rules out provisioning hosts from list of machines suitable to run this VM.",
Are you sure the description is correct ?
check y suggestion in the doc part.

2021-09-13 10:11 UTC, jaypif commented on website/docs/r/virtual_machine.html.markdown
> +* `sched_requirements` - (Optional) A boolean expression to select the hosts that could run the VM.
I do prefer something like: Scheduling requirements to deploy the resource following specific rule.

2021-09-14 04:45 UTC, treywelsh commented
By the way, I added `sched_ds_requirements` attribute from placement section

2021-09-25 17:41 UTC, CRASH-Tech commented
Please, appruve this PR

2021-09-27 07:51 UTC, jaypif commented on website/docs/r/template.html.markdown
> +* `sched_ds_requirements` - (Optional) Storage requirements to deploy the resource following specific rule.
It is "storage placement requirements" to be correct

2021-09-27 07:51 UTC, jaypif commented on opennebula/shared_schemas.go
> +		Description: "Storage requirements to deploy the resource following specific rule",
It is "storage placement requirements" to be correct

2021-10-01 12:52 UTC, jaypif requested changes
Add Unit test on these new attributes

2021-10-12 17:07 UTC, treywelsh commented
It seems that the update behaviour may be improved in case of key deletion.
For now in this PR, in order to delete an element `key="value1"` I send a template with the empty value: `key=""`
Then, I call update method with merge behaviour (other behavior available is replace)

However, implement this behaviour will complexify the code: I would need to collect the template of the VM, delete the element, then call update with replace behavior.

2021-10-14 15:23 UTC, treywelsh commented
I modified the update behavior to allow to delete the templates attributes from the VM and Template ressources.

2021-11-19 12:46 UTC, jaypif approved these changes

2021-11-19 14:29 UTC, merged