F-32: add virtual router resource
OpenNebula/terraform-provider-opennebula pull request #170
Opened 2021-10-15 10:40 UTC by treywelsh

Add new virtual router resource and modify related resource: template and virtual machine

2021-10-15 10:44 UTC, treywelsh commented
@perrfect @turb0steve If you want to give it a try and some feedback, here is a basic implementation of the virtual router resource.

However I need to test it more and add acceptance test

2022-04-19 13:24 UTC, frousselet commented
Hi @treywelsh,

As seen together, I think a better approach is to follow the Sunstone workflow in order to keep the Terraform provider and the GUI consistant:

1 - Create a new Virtual Router template (1 resource)
2 - Instantiate it (1 resource)

```hcl
resource "opennebula_virtual_router_template" "test" {
  name        = "testacc-vr"
  description = "This is an example of virtual router"

  permissions = "642"
  group       = "oneadmin"

  timeout = 5
  lock    = "USE"
  nic {
    network_id = opennebula_virtual_network.test.id
    ip         = "172.16.100.10"
  }
}

resource "opennebula_virtual_router" "test" {
  template_id = opennebula_virtual_router_template.test.id

  # ...

  number_of_instances = 3
}
```

Also, we might move `opennebula_template` to `opennebula_virtual_machine_template`.

2022-05-13 12:30 UTC, treywelsh commented
I realize that it still miss some stuffs:
- externalize NIC ressource from virtual router: it's how we deal with sub resources now
- test to do: vrouter creation with NICs attach, then add an instance and check if it has nic attached

2022-05-18 13:37 UTC, treywelsh commented
From this comment, I pushed is a full rework of the virtual router resource:

- introduce more resources, here is the full list: opennebula_virtual_router, opennebula_virtual_router_nic, opennebula_virtual_router_instance_template, opennebula_virtual_router_instance
- introduce provider configuration structure: we need to carry more facilities between CRUD methods: we need some locking to avoid conflicts in resources creation/deletion
  Locking facilities helps to prevent errors when opennebula_virtual_router_instance and opennebula_virtual_router_nic are created simultaneously.

The downside of introducing basic locking like I did is that virtual router deployement may be slower than needed due to the fact that virtual router instances will be created sequentially.
With locking I tried to prevent several virtual router nics to be attached at the same time, and prevent virtual router nic and instances to be attached at the same time.
But virtual router instance could be created in parallel.

An idea to fix this could be to add more informations to the locking code: i.e. keeping track of the element type that acquired the lock (nic or instance). 
To move forward I let this problem for a future PR.

2022-05-19 11:16 UTC, treywelsh commented
I may continue to test it a bit during but I think it's enough satisfying for a review.
I hope I didn't make too much mistakes in the documentation part.

2022-05-20 11:06 UTC, frousselet requested changes

2022-05-20 11:06 UTC, frousselet commented on website/docs/r/virtual_router_instance_template.markdown
> +# opennebula_virtual_router_nic
Hmm... Copy-paste I guess...

2022-05-20 12:12 UTC, treywelsh commented on website/docs/r/virtual_router_instance_template.markdown
> +# opennebula_virtual_router_nic
The whole page was wrong, I reworked it

2022-05-20 12:21 UTC, frousselet approved these changes

2022-05-20 21:08 UTC, frousselet approved these changes

2022-05-20 21:14 UTC, frousselet commented
@treywelsh,
Could you add a comment with `terraform apply` and `terraform destroy` outputs please?

2022-05-23 08:29 UTC, treywelsh commented
```
resource "opennebula_virtual_router_instance_template" "test" {
  name        = "testacc-vr-template"
  permissions = "642"
  group       = "oneadmin"
  cpu         = "0.5"
  vcpu        = "1"
  memory      = "512"

  context = {
    dns_hostname = "yes"
    network      = "YES"
  }

  graphics {
    keymap = "en-us"
    listen = "0.0.0.0"
    type   = "VNC"
  }

  os {
    arch = "x86_64"
    boot = ""
  }

  tags = {
    env = "prod"
  }
}

resource "opennebula_virtual_network" "network1" {
  name   = "test-net1"
  type   = "bridge"
  bridge = "onebr"
  mtu    = 1500
  ar {
    ar_type = "IP4"
    size    = 12
    ip4     = "172.16.100.130"
  }
  permissions     = "642"
  group           = "oneadmin"
  security_groups = [0]
  clusters        = [0]
}

resource "opennebula_virtual_router_instance" "test" {
  name        = "testacc-vr-virtual-machine"
  group       = "oneadmin"
  permissions = "642"
  memory      = 128
  cpu         = 0.1

  virtual_router_id = opennebula_virtual_router.test.id
}

resource "opennebula_virtual_router" "test" {
  name        = "testacc-vr"
  permissions = "642"
  group       = "oneadmin"

  instance_template_id = opennebula_virtual_router_instance_template.test.id

  tags = {
    customer = "1"
  }
}

```

Plan:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # opennebula_virtual_network.network1 will be created
  + resource "opennebula_virtual_network" "network1" {
      + automatic_vlan_id = (known after apply)
      + bridge            = "onebr"
      + clusters          = [
          + 0,
        ]
      + description       = (known after apply)
      + dns               = (known after apply)
      + gateway           = (known after apply)
      + gid               = (known after apply)
      + gname             = (known after apply)
      + group             = "oneadmin"
      + guest_mtu         = 1500
      + hold_size         = (known after apply)
      + id                = (known after apply)
      + ip_hold           = (known after apply)
      + mtu               = 1500
      + name              = "test-net1"
      + network_mask      = (known after apply)
      + permissions       = "642"
      + physical_device   = (known after apply)
      + reservation_size  = (known after apply)
      + reservation_vnet  = (known after apply)
      + security_groups   = [
          + 0,
        ]
      + type              = "bridge"
      + uid               = (known after apply)
      + uname             = (known after apply)
      + vlan_id           = (known after apply)

      + ar {
          + ar_type                = "IP4"
          + computed_global_prefix = (known after apply)
          + computed_ip6           = (known after apply)
          + computed_mac           = (known after apply)
          + computed_ula_prefix    = (known after apply)
          + id                     = (known after apply)
          + ip4                    = "172.16.100.130"
          + size                   = 12
        }
    }

  # opennebula_virtual_router.test will be created
  + resource "opennebula_virtual_router" "test" {
      + gid                  = (known after apply)
      + gname                = (known after apply)
      + group                = "oneadmin"
      + id                   = (known after apply)
      + instance_template_id = (known after apply)
      + name                 = "testacc-vr"
      + permissions          = "642"
      + tags                 = {
          + "customer" = "1"
        }
      + timeout              = 3
      + uid                  = (known after apply)
      + uname                = (known after apply)
    }

  # opennebula_virtual_router_instance.test will be created
  + resource "opennebula_virtual_router_instance" "test" {
      + cpu               = 0.1
      + gid               = (known after apply)
      + gname             = (known after apply)
      + group             = "oneadmin"
      + id                = (known after apply)
      + lcmstate          = (known after apply)
      + memory            = 128
      + name              = "testacc-vr-virtual-machine"
      + on_disk_change    = "swap"
      + pending           = false
      + permissions       = "642"
      + state             = (known after apply)
      + template_disk     = (known after apply)
      + timeout           = 3
      + uid               = (known after apply)
      + uname             = (known after apply)
      + vcpu              = (known after apply)
      + virtual_router_id = (known after apply)

      + vmgroup {
          + role       = (known after apply)
          + vmgroup_id = (known after apply)
        }
    }

  # opennebula_virtual_router_instance_template.test will be created
  + resource "opennebula_virtual_router_instance_template" "test" {
      + context     = {
          + "dns_hostname" = "yes"
          + "network"      = "YES"
        }
      + cpu         = 0.5
      + gid         = (known after apply)
      + gname       = (known after apply)
      + group       = "oneadmin"
      + id          = (known after apply)
      + memory      = 512
      + name        = "testacc-vr-template"
      + permissions = "642"
      + reg_time    = (known after apply)
      + tags        = {
          + "env" = "prod"
        }
      + uid         = (known after apply)
      + uname       = (known after apply)
      + vcpu        = 1

      + graphics {
          + keymap = "en-us"
          + listen = "0.0.0.0"
          + port   = (known after apply)
          + type   = "VNC"
        }

      + os {
          + arch = "x86_64"
        }

      + vmgroup {
          + role       = (known after apply)
          + vmgroup_id = (known after apply)
        }
    }

Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opennebula_virtual_router_instance_template.test: Creating...
opennebula_virtual_network.network1: Creating...
opennebula_virtual_router_instance_template.test: Creation complete after 1s [id=1]
opennebula_virtual_router.test: Creating...
opennebula_virtual_router.test: Creation complete after 0s [id=0]
opennebula_virtual_router_instance.test: Creating...
opennebula_virtual_network.network1: Still creating... [10s elapsed]
opennebula_virtual_router_instance.test: Still creating... [10s elapsed]
opennebula_virtual_network.network1: Creation complete after 11s [id=1]
opennebula_virtual_router_instance.test: Creation complete after 13s [id=0]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
```

And destroy:
```
opennebula_virtual_router_instance_template.test: Refreshing state... [id=1]
opennebula_virtual_network.network1: Refreshing state... [id=1]
opennebula_virtual_router.test: Refreshing state... [id=0]
opennebula_virtual_router_instance.test: Refreshing state... [id=0]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # opennebula_virtual_network.network1 will be destroyed
  - resource "opennebula_virtual_network" "network1" {
      - bridge          = "onebr" -> null
      - clusters        = [
          - 0,
        ] -> null
      - gid             = 0 -> null
      - gname           = "oneadmin" -> null
      - group           = "oneadmin" -> null
      - guest_mtu       = 1500 -> null
      - id              = "1" -> null
      - mtu             = 1500 -> null
      - name            = "test-net1" -> null
      - permissions     = "642" -> null
      - security_groups = [
          - 0,
        ] -> null
      - type            = "bridge" -> null
      - uid             = 0 -> null
      - uname          [...]

2022-05-23 09:32 UTC, merged