Add support for ipv6 address information
OpenNebula/terraform-provider-opennebula pull request #194
Opened 2022-01-12 14:11 UTC by danimo

Expose computed_ip6_global and computed_ip6_link next to computed_ip

Signed-off-by: Daniel Molkentin <daniel@molkentin.de>

2022-01-12 15:26 UTC, jaypif requested changes
Hi,

thank you for you contribution.

Can you :
- Open an issue to track this new feature and add the prefix `[F-XXX]` in you PR and commit messages where `XXX` is the ID of the feature.
- Add the new attribute into the resource doc page with example
- Add unit tests

Thank you

Best regards

2022-01-12 16:07 UTC, danimo commented
@jaypif Can do. I also started on doing tests, but since the suite fails to run both locally and in actions, I am stuck there. Can you advise how to make them pass?

2022-01-12 16:10 UTC, jaypif commented
Hi @danimo 

No worries, the CI fails for the 6.2 release, it is a know issue which require an update on the GOCA (GO binding for ones) dependency.
Your tests must pass the 5.12 release. If it is the case, it is ok.

Thank you

2022-01-12 17:49 UTC, albert0marti commented
Great contribution, folks!

2022-05-23 13:00 UTC, frousselet commented
Cherry-picked @danimo commits and continue to work here: #261

2022-05-23 13:00 UTC, closed without merging