F 235 vm sizing attrs
OpenNebula/terraform-provider-opennebula pull request #236
Opened 2022-04-08 19:20 UTC by treywelsh

Update of #218

The CI will fail until we merge #211 

Closes #235

2022-04-14 12:15 UTC, treywelsh commented
The CI will fail until we merge #211 :
```
=== RUN   TestAccVirtualMachine
    testing.go:654: Step 1 error: Check failed: Check 5/29 error: opennebula_virtual_machine.test: Attribute 'memory' expected "196", got "128"
```

This seems to be due to the fact that acceptance test tried to test VM resizing, but resizing is not implemented for now.

2022-05-23 13:01 UTC, frousselet requested changes
Please rebase on master

2022-05-23 13:12 UTC, frousselet requested changes
Missing CHANGELOG

2022-05-23 13:18 UTC, frousselet approved these changes

2022-05-23 15:44 UTC, frousselet approved these changes

2022-05-23 15:45 UTC, merged