update dependencies and check for virtual network state
OpenNebula/terraform-provider-opennebula pull request #270
Opened 2022-05-19 16:41 UTC by treywelsh

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

This PR add conditional virtual network checks.
Goca dependency is also updated in this PR.

Close #266 

### New or Affected Resource(s)

- opennebula_virtual_network

### Checklist

- [ ] I have created an issue and I have mentioned it in `References`
- [ ] My code follows the style guidelines of this project (use `go fmt`)
- [ ] My changes generate no new warnings or errors
- [ ] I have updated the unit tests and they pass succesfuly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation (if needed)
- [ ] I have updated the changelog file

2022-05-19 17:11 UTC, treywelsh commented
TODO: refact resource with sdk v2 facilities to introduce timeout

2022-05-20 11:17 UTC, frousselet approved these changes

2022-05-20 11:19 UTC, frousselet requested changes
Could you update the CHANGELOG please?

2022-05-20 11:58 UTC, frousselet approved these changes

2022-05-20 12:21 UTC, merged