Allow setting of first ip for network reservations
OpenNebula/terraform-provider-opennebula pull request #274
Opened 2022-05-23 13:05 UTC by treywelsh

This is a PR that apply some small changes to https://github.com/OpenNebula/terraform-provider-opennebula/pull/185 authored by @danhigham

2022-05-24 15:42 UTC, treywelsh commented
This PR introduce the `reservation_ar_id` attribute.
It's easy to retrieve with an already existing AR but we may want to be able create a reservation at the same time that we create the AR in the parent network.
In addition, it's not possible to rely on address range order to guess the ID (ARs are stored in a TypeSet. We could store them in a TypeList instead, but keep AR ordering through future AR modification is not so funny).

I don't see any easy and clean way to work with `reservation_ar_id` other than externalize the address range to it's own resource: #279

2022-06-03 08:30 UTC, treywelsh commented
depends on #279 should be scheduled for 1.0 release

2022-08-24 15:58 UTC, treywelsh commented
rebased on top of #306 until it's merged to make this PR move forward

2022-08-25 14:33 UTC, treywelsh commented on website/docs/r/virtual_network.html.markdown
> +<<<<<<< HEAD
remove this

2022-08-30 14:39 UTC, frousselet commented on CHANGELOG.md
> +* resources/opennebula_virtual_network: Set first IP and address range ID for address reservations
Add attributes `reservation_first_ip` and `reservation_ar_id`

2022-08-30 14:46 UTC, frousselet requested changes

2022-08-30 14:46 UTC, frousselet commented on CHANGELOG.md
> +* resources/opennebula_virtual_network: Set first IP and address range ID for address reservations
Add attributes `reservation_first_ip` and `reservation_ar_id`.

2022-09-02 12:30 UTC, frousselet approved these changes

2022-09-02 12:30 UTC, merged