B #289: VM: fix missing NIC generation
OpenNebula/terraform-provider-opennebula pull request #290
Opened 2022-06-14 12:18 UTC by treywelsh

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

Fix NIC not attached anymore.

### References

Close #289 

### New or Affected Resource(s)

- opennebula_virtual_machine

### Checklist

- [ ] I have created an issue and I have mentioned it in `References`
- [ ] My code follows the style guidelines of this project (use `go fmt`)
- [ ] My changes generate no new warnings or errors
- [ ] I have updated the unit tests and they pass succesfuly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation (if needed)
- [ ] I have updated the changelog file

2022-06-14 12:58 UTC, treywelsh commented
The CI didn't failed on VM NICs acceptance test cases. This seems a bit weird at first glance.

2022-06-23 12:55 UTC, frousselet requested changes
Please also consolidate acceptance tests to prevent that kind of issues

2022-06-28 10:04 UTC, treywelsh commented
#304 explains why we didn't see the problem via the acceptance tests

2022-06-28 12:10 UTC, frousselet approved these changes

2022-06-28 12:11 UTC, merged