F-322: add `opennebula_templates` datasource
OpenNebula/terraform-provider-opennebula pull request #388
Opened 2023-01-05 16:38 UTC by treywelsh

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

Add templates datasource which allows to manage a filtered list of templates.

### References

Close #322 

### New or Affected Resource(s)

- data opennebula_templates

### Checklist

- [ ] I have created an issue and I have mentioned it in `References`
- [ ] My code follows the style guidelines of this project (use `go fmt`)
- [ ] My changes generate no new warnings or errors
- [ ] I have updated the unit tests and they pass succesfuly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation (if needed)
- [ ] I have updated the changelog file

2023-02-01 19:25 UTC, treywelsh commented
`name_regex` attribute added, and a code duplication reduced

2023-03-07 09:06 UTC, frousselet requested changes

2023-03-07 09:06 UTC, frousselet commented on website/docs/d/templates.html.markdown
> +* `name_regex` - (Optional) Filter templates by name with a RE2 a regular expression.
I guess there is a typo here

2023-03-07 15:28 UTC, frousselet approved these changes

2023-03-07 15:40 UTC, merged