Rename cpumodel to cpu_model
OpenNebula/terraform-provider-opennebula pull request #454
Opened 2023-05-16 13:23 UTC by TGM

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

Rename virtual machine resource attribute `cpumodel` to `cpu_model`

### References

#451 

### New or Affected Resource(s)

- opennebula_virtual_machine

### Checklist

- [ ] I have created an issue and I have mentioned it in `References`
- [ ] My code follows the style guidelines of this project (use `go fmt`)
- [ ] My changes generate no new warnings or errors
- [ ] I have updated the unit tests and they pass succesfuly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation (if needed)
- [ ] I have updated the changelog file

2023-05-19 15:19 UTC, treywelsh commented
If we do this, we'll need to deprecate `cpumodel`, it would be nice to see if some others users are ok with this change or not, and then this PR should be completed with deprecations, documentation and changelog :)

If @frousselet is ok we could plan this in one of the future releases

2023-05-25 13:04 UTC, frousselet commented
Ok for me.

@TGM, could you create an issue first please?
Also, the documentation needs to be updated.

2023-07-18 15:42 UTC, treywelsh requested changes
we can't only rename existing attribute, we need to deprecate cpumodel, and at the same time add a new attribute cpu_model. We replace an attributes on several provider releases.
If we don't do that, a bunch of users will complain that they have errors without any previous warning that something was about to change it the current release of the provider.

In addition golang variables have a special case: https://go.dev/doc/effective_go#mixed-caps

And last, the documentation and the changelog should be updated.

As a side note, this PR doesn't fix a bug and it don't address these problems: 
- https://github.com/OpenNebula/terraform-provider-opennebula/issues/451#issuecomment-1544179095
- https://github.com/OpenNebula/terraform-provider-opennebula/issues/451#issuecomment-1551331822
  I don't think it's a big deal, probably a missing check on present but empty values

But we may want to open an other separate PR to fix these last two problems

2023-07-18 15:42 UTC, treywelsh commented on opennebula/resource_opennebula_template.go
> +		cpu_model := d.Get("cpu_model").([]interface{})
golang variable should be named `cpuModel`, not `cpumodel` nor `cpu_model`

2023-07-18 15:42 UTC, treywelsh commented on opennebula/resource_opennebula_template.go
> +			cpu_modelconfig := cpu_model[i].(map[string]interface{})
variable name shloud be `cpuModelConfig`

2023-07-18 15:42 UTC, treywelsh commented on opennebula/shared_schemas.go
> +func cpu_modelSchema() *schema.Schema {
`cpuModelSchema`

2023-08-23 00:08 UTC, closed without merging