Add CPU model support
OpenNebula/terraform-provider-opennebula pull request #99
Opened 2021-01-18 14:02 UTC by ankur-gupta-guavus

@jaypif Can you please review this PR for adding CPU model support ?

2021-01-18 15:07 UTC, jaypif requested changes
thanks for the PR.
In addition to my remarks, can you also add a test case in the test file ?

2021-01-18 15:07 UTC, jaypif commented on opennebula/shared_schemas.go
> +                Computed:    true,
remove this to avoid unexpected behavior during a change (if not set by the user but set by OpenNebula Terraform will see a change)

2021-01-18 15:07 UTC, jaypif commented on opennebula/resource_opennebula_virtual_machine.go
> +                        "cpumodel": cpumodelSchema(),
run `make fmt` to fix indent

2021-01-18 15:07 UTC, jaypif commented on opennebula/shared_schemas.go
> +        cpumodel, _ := vmTemplate.GetCPUModel(vmk.Model)
indent to be fixed

2021-01-18 15:14 UTC, ankur-gupta-guavus commented
@jaypif i have added suggested changes, I will add test case too in sometime.

2021-01-19 05:45 UTC, ankur-gupta-guavus commented
@jaypif I have added test case

2021-01-27 14:00 UTC, jaypif commented
@ankur-gupta-guavus there is a panic during CI.

Can you fix it ?

2021-01-28 07:32 UTC, ankur-gupta-guavus commented
@jaypif panic during CI was due to type assertion for nic. I have not made any changes there. However, still to move past panic I have added a test to check whether interface value holds correct specific type, build is in queue state. Will see if that resolves it.

2021-01-29 10:15 UTC, jaypif commented
Indeed this is weird

Can you rebase your branch to the last master just to be sure ? 

thanks @ankur-gupta-guavus

2021-02-02 10:37 UTC, jaypif commented
Hi @ankur-gupta-guavus 

For an unknown reason the provider used an invalid version of One Goca.
We fixed it thanks to #102 

Can you rebase again your PR on master to fix CI issues ?

Thanks and sorry for the inconvenience

2021-02-02 13:23 UTC, ankur-gupta-guavus commented
@jaypif Rebase was getting a bit ugly, so i will close this PR and open a [new one](https://github.com/OpenNebula/terraform-provider-opennebula/pull/103)

2021-02-02 13:23 UTC, closed without merging

2021-02-02 13:24 UTC, ankur-gupta-guavus commented
Opened a [new one](https://github.com/OpenNebula/terraform-provider-opennebula/pull/103) with latest master